# @package _group_

common:
  fp16: false
  log_format: json
  log_interval: 200
  seed: 1337
  tensorboard_logdir: tblog

checkpoint:
  restore_file: /disk/scratch1/ramons/data/hubert_models/hubert_base_ls960.pt
  #save_interval_updates: 25000
  save_interval_updates: 100
  #keep_interval_updates: 1
  no_epoch_checkpoints: true
  reset_optimizer: true

task:
  _name: hubert_pretraining
  data: ???
  label_dir: ???
  labels: ???
  label_rate: ${model.label_rate}
  sample_rate: 16000
  max_sample_size: 250000
  min_sample_size: 32000
  pad_audio: false
  random_crop: true
  normalize: false # must be consistent with extractor

dataset:
  num_workers: 6
  max_tokens: 1400000
  skip_invalid_size_inputs_valid_test: true
  validate_interval: 1
  #validate_interval_updates: 10000
  required_batch_size_multiple: 4
  valid_subset: "valid,valid_en"


criterion:
  _name: hubert
  pred_masked_weight: 1.0
  pred_nomask_weight: 0.0
  loss_weights: [10,]

optimization:
  max_update: 400000
  lr: [0.0005]
  clip_norm: 10.0

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-06
  weight_decay: 0.01
  lr: [0.0005]

lr_scheduler:
  _name: polynomial_decay
  warmup_updates: 32000

model:
  _name: hubert
  checkpoint_kpt: "/disk/scratch1/ramons/data/hubert_models/hubert_base_ls960.pt"
  freeze_param: "layer10"
  label_rate: ???
  skip_masked: false
  skip_nomask: false
  mask_prob: 0.80
  extractor_mode: default
  conv_feature_layers: '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2'
  final_dim: 256
  encoder_layerdrop: 0.05
  dropout_input: 0.1
  dropout_features: 0.1
  dropout: 0.1
  attention_dropout: 0.1
  feature_grad_mult: 0.1
  untie_final_proj: true
  activation_dropout: 0.0

hydra:
  job:
    config:
      override_dirname:
        kv_sep: '-'
        item_sep: '__'
        exclude_keys:
          - run
          - task.data
          - task.label_dir
  run:
    dir: /disk/scratch1/ramons/data/hubert_models/libri_100/LR_${optimizer.lr}_l9500_fb
  sweep:
    dir: /disk/scratch1/ramons/data/hubert_models/french
    #subdir: ${hydra.job.config_name}__${hydra.job.override_dirname}__${optimizer.lr}
    subdir: LR
